fix(ssl): set sni when using ssl verify
Tieske/lua-resty-luasocket pull request #3
Opened 2023-04-20 07:47 UTC by windmgc

It seems that without SNI settings the server certificate verification will fail.

A simple reproduce example:

```
local http = require "resty.luasocket.http"
local resty_luasocket = require "resty.luasocket"
local inspect = require "inspect"

resty_luasocket.force_luasocket("timer", true)

print(ngx.get_phase())

local client = http.new()

local res, err = client:request_uri("https://www.google.com/", {
        method = "GET",
        ssl_verify = true,
})

print(res)
print(err)

(kong-dev) ubuntu@ip-172-31-93-219:~/kong-ee$ resty g.lua
timer
2023/04/20 06:30:28 [warn] 1368916#0: *2 [lua] _G write guard:12: writing a global Lua variable ('socket') which may lead to race conditions between concurrent requests, so prefer the use of 'local' variables
stack traceback:
        [C]: at 0x7f93889653e0
        [C]: in function 'require'
        ...ong-ee/bazel-bin/build/kong-dev/share/lua/5.1/socket.lua:12: in main chunk
        [C]: in function 'require'
        ...in/build/kong-dev/share/lua/5.1/resty/luasocket/init.lua:237: in function 'ngx_socket_tcp'
        ...ee/bazel-bin/build/kong-dev/share/lua/5.1/resty/http.lua:133: in function 'new'
        g.lua:9: in function 'file_gen'
        init_worker_by_lua:45: in function <init_worker_by_lua:43>
        [C]: in function 'xpcall'
        init_worker_by_lua:52: in function <init_worker_by_lua:50>, context: ngx.timer

certificate verify failed
```

2023-04-20 07:52 UTC, windmgc commented
Since I'm not very much familiar with luasec, not sure if this is the right way to do.
@Tieske Could you please help check that?

2023-04-23 22:27 UTC, Tieske commented
If you change the test to;
```lua
local res, err = client:request_uri("https://amazon.com/", {
        method = "GET",
        ssl_verify = true,
})
```
then it works. So there's something different between `google.com` and `amazon.com`.

2023-04-23 22:38 UTC, Tieske requested changes
since SNI is unset, it seems the `google.com` server is responding with a cert that is not for `google.com`.  So apparently the server is serving multiple names from the same IP addresses. Hence the proper solution is to set the server name indication, if it was given, such that the backend can reply with the proper cert. Even if we are not verifying it on our end.

2023-04-23 22:38 UTC, Tieske commented on lib/resty/luasocket/init.lua
> +      end
The check should not be on `verify` but on whether an SNI was provided;
```suggestion
      if server_name then
        sock:sni(server_name)
      end
```

2023-04-23 22:38 UTC, Tieske commented on CHANGELOG.md
> +- fix: set sni when using ssl verify
```suggestion
- fix: set sni when a server-name is provided
```

2023-04-24 05:59 UTC, windmgc commented
@Tieske Thanks for the investigation! That makes sense.

Having a closer look at the implementation of `lua-resty-http`, in this test case(without specifying the ssl_server_name), the server name is provided based on the host name parsed from the URI, so the server name will always be a non-nil value

https://github.com/ledgetech/lua-resty-http/blob/4ab4269cf442ba52507aa2c718f606054452fcad/lib/resty/http.lua#L907-L923

2023-04-24 10:52 UTC, Tieske approved these changes

2023-04-24 10:56 UTC, merged